### PR TITLE
chore: allow showing hidden files

### PR DESCRIPTION
**Pull request by lorenzo-cavazzi**
Allow showing hidden files in the JupyterLab file browser.

### CODE REVIEW

**Comment by lorenzo-cavazzi** [comment]
This seems to work, but I don't see the toggle to show/hide hidden files as mentioned here https://jupyterlab.readthedocs.io/en/stable/user/files.html#displaying-hidden-files
The hidden files are always visible.

Screenshot_20220707_171343

Screenshot_20220707_171513

**Review by olevski — DISMISSED** [review]

**Comment by lorenzo-cavazzi** [comment]
Using the latest version of our RenkuLab Docker images (i.e. starting from a newer version of the Juypter Docker images with JupyterLab 3.3.4 ) solves the previous problem: the files are hidden by default and the user can tick a new "Show Hidden Files" option in the "View" menu  :tada: 

It's testable on https://lorenzo.dev.renku.ch using the following custom template:
* Repository: `https://github.com/SwissDataScienceCenter/renku-project-template`
* Branch: `000-bump-images-version`

I'll tag a new version of the templates from https://github.com/SwissDataScienceCenter/renku-project-template/pull/146

Screenshot_20220808_114252

**Review by olevski — APPROVED** [review]

**Comment by olevski** [comment]
@lorenzo-cavazzi there is no `#deploy persist` here. The acceptance tests run jupyter servers and test simple scenarios. If those pass then things are fine.

If you want to test with renku then you can do that by deploying yourself or publishing a helm chart and doing a PR in renku-notebooks.

**Review by olevski — APPROVED** [review]

**Comment by lorenzo-cavazzi** [comment]
We updated the template images a while ago, I think we can now consider merging this (unless there are reasons to hold-on @olevski )

**Pull request merged**
